name: build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          always-auth: true
          cache: npm
          node-version: 22
      - name: Install requirements
        run: npm i
      - name: Run eleventy
        run: npx @11ty/eleventy
      - name: Deploy to GitHub Pages
        if: success() && github.event_name == 'push'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          allow_empty_commit: false
          build_dir: _site
          target_branch: gh-pages
          fqdn: matematiikkakilpailut.fi
          jekyll: false
          dry_run: false
          verbose: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
